export const icons = {
  // Actions
  'add': '➕',
  'remove': '➖',
  'edit': '✏️',
  'delete': '🗑️',
  'save': '💾',
  'copy': '📋',
  'cut': '✂️',
  'paste': '📄',
  'undo': '↶',
  'redo': '↷',
  'refresh': '🔄',
  'sync': '🔄',
  'download': '⬇️',
  'upload': '⬆️',
  'share': '📤',
  'print': '🖨️',
  'search': '🔍',
  'filter': '🔽',
  'sort': '🔀',
  'settings': '⚙️',
  'config': '🔧',
  'tools': '🛠️',
  
  // Navigation
  'home': '🏠',
  'back': '⬅️',
  'forward': '➡️',
  'up': '⬆️',
  'down': '⬇️',
  'left': '⬅️',
  'right': '➡️',
  'menu': '☰',
  'close': '✖️',
  'expand': '⬇️',
  'collapse': '⬆️',
  'fullscreen': '⛶',
  'exit-fullscreen': '⛷',
  
  // Status
  'success': '✅',
  'error': '❌',
  'warning': '⚠️',
  'info': 'ℹ️',
  'help': '❓',
  'loading': '⏳',
  'spinner': '🔄',
  'check': '✓',
  'cross': '✗',
  'star': '⭐',
  'heart': '❤️',
  'like': '👍',
  'dislike': '👎',
  
  // Communication
  'mail': '📧',
  'message': '💬',
  'chat': '💭',
  'phone': '📞',
  'video': '📹',
  'camera': '📷',
  'microphone': '🎤',
  'speaker': '🔊',
  'mute': '🔇',
  'notification': '🔔',
  'bell': '🔔',
  
  // Files & Folders
  'file': '📄',
  'folder': '📁',
  'folder-open': '📂',
  'document': '📃',
  'image': '🖼️',
  'video-file': '🎬',
  'audio': '🎵',
  'zip': '🗜️',
  'pdf': '📕',
  'code': '💻',
  
  // User & People
  'user': '👤',
  'users': '👥',
  'profile': '👤',
  'account': '👤',
  'team': '👥',
  'group': '👥',
  'admin': '👑',
  'guest': '👤',
  
  // Security
  'lock': '🔒',
  'unlock': '🔓',
  'key': '🔑',
  'shield': '🛡️',
  'security': '🔐',
  'password': '🔑',
  'fingerprint': '👆',
  'eye': '👁️',
  'eye-off': '🙈',
  
  // Time & Calendar
  'calendar': '📅',
  'clock': '🕐',
  'time': '⏰',
  'timer': '⏲️',
  'stopwatch': '⏱️',
  'schedule': '📋',
  'date': '📅',
  'today': '📅',
  
  // Weather
  'sun': '☀️',
  'moon': '🌙',
  'cloud': '☁️',
  'rain': '🌧️',
  'snow': '❄️',
  'storm': '⛈️',
  'wind': '💨',
  'temperature': '🌡️',
  
  // Transport
  'car': '🚗',
  'bus': '🚌',
  'train': '🚆',
  'plane': '✈️',
  'ship': '🚢',
  'bike': '🚲',
  'walk': '🚶',
  'location': '📍',
  'map': '🗺️',
  'compass': '🧭',
  
  // Technology
  'wifi': '📶',
  'bluetooth': '📶',
  'battery': '🔋',
  'power': '⚡',
  'signal': '📶',
  'network': '🌐',
  'database': '🗄️',
  'server': '🖥️',
  'cloud-storage': '☁️',
  'backup': '💾',
  
  // Shopping & Money
  'cart': '🛒',
  'bag': '🛍️',
  'credit-card': '💳',
  'money': '💰',
  'coin': '🪙',
  'price': '💲',
  'sale': '🏷️',
  'gift': '🎁',
  'receipt': '🧾',
  
  // Entertainment
  'music': '🎵',
  'play': '▶️',
  'pause': '⏸️',
  'stop': '⏹️',
  'next': '⏭️',
  'previous': '⏮️',
  'volume': '🔊',
  'game': '🎮',
  'tv': '📺',
  'radio': '📻',
  
  // Health & Medical
  'health': '🏥',
  'heart-rate': '💓',
  'medicine': '💊',
  'first-aid': '🩹',
  'doctor': '👨‍⚕️',
  'hospital': '🏥',
  'ambulance': '🚑',
  
  // Education
  'book': '📚',
  'education': '🎓',
  'school': '🏫',
  'student': '👨‍🎓',
  'teacher': '👨‍🏫',
  'pencil': '✏️',
  'ruler': '📏',
  'calculator': '🧮',
  
  // Food & Drink
  'food': '🍽️',
  'coffee': '☕',
  'tea': '🍵',
  'water': '💧',
  'restaurant': '🍽️',
  'kitchen': '🍳',
  'recipe': '📝',
  
  // Sports & Fitness
  'fitness': '💪',
  'gym': '🏋️',
  'running': '🏃',
  'cycling': '🚴',
  'swimming': '🏊',
  'football': '⚽',
  'basketball': '🏀',
  'tennis': '🎾',
  
  // Miscellaneous
  'fire': '🔥',
  'rocket': '🚀',
  'magic': '✨',
  'diamond': '💎',
  'crown': '👑',
  'trophy': '🏆',
  'medal': '🏅',
  'flag': '🚩',
  'bookmark': '🔖',
  'tag': '🏷️',
  'pin': '📌',
  'paperclip': '📎',
  'link': '🔗',
  'chain': '⛓️',
  'globe': '🌍',
  'earth': '🌎',
  'world': '🌏'
} as const;

export type IconName = keyof typeof icons;